### ISSUE TITLE
[BUG] Splat.Autofac - Method not found: 'Splat.IFullLogger Splat.LogHost.get_Default() for avalonia

### ISSUE THREAD

**Issue by BananaRush** [reactiveui/splat#672]
Hello, getting an exception after running avalonia project (Hello Word).

Steps To Reproduce
1. Create Project Avalonia UI for .NET 5 
2. Install-Package Splat.Autofac -Version 10.0.1
3. Run Project

Environment
Windows 10 Pro

dependencies

```XML
    <PackageReference Include="Avalonia" Version="0.10.0" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.0" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.0" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.0" />
    <PackageReference Include="Splat" Version="10.0.1" />
    <PackageReference Include="Splat.Autofac" Version="10.0.1" />
```

```
Full

System.TypeInitializationException: "The type initializer for 'ReactiveUI.RxApp' threw an exception
MissingMethodException: Method not found: 'Splat.IFullLogger Splat.LogHost.get_Default()

StackTrace

   at ReactiveUI.RxApp.set_MainThreadScheduler(IScheduler value) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\RxApp.cs:line 167
   at Avalonia.ReactiveUI.AppBuilderExtensions.<>c__0`1.<UseReactiveUI>b__0_0(TAppBuilder _) in /_/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs:line 21
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 306
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at HelloWorld.Program.Main(String[] args) in C:\Users\Alexander\source\repos\Kiosk\HelloWorld\Program.cs:line 10
```
code 
```CSharp
    class Program
    {
        public static void Main(string[] args) =>
            BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);
        

        public static AppBuilder BuildAvaloniaApp() =>
            AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .UseReactiveUI();
    }
```

**Comment by glennawatson** [comment]
You'll likely want to ask the avalonia guys to schedule a update to the latest rxui at some point. There was a breaking change. For the moment remove the splat reference

**Comment by BananaRush** [comment]
I removed splat and everything worked, thank you!
