### ISSUE TITLE
[BUG]  When i upgrade Splat from 11.1.1 to 13.1.10 there has an exception

### ISSUE THREAD

**Issue by Luoyingliang** [reactiveui/splat#771]
**Describe the bug**
When i upgrade Splat from 11.1.1 to 13.1.10 there has an exception, is there any solution?

**Steps To Reproduce**
this is my older version project, i want to upgrade splat from 11.1.1 to 13.1.10.

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - OS: Windows 10 20h2
 - SDK : .NET 6 RC1
 - other dependencies:
 -  Splat.DryIoC 
 -  Splat.NLog

**Additional context**
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Splat.DryIoc.DryIocDependencyResolver.Register(Func`1 factory, Type serviceType, String contract)
   at Splat.DependencyResolverMixins.RegisterConstant(IMutableDependencyResolver resolver, Object value, Type serviceType, String contract) in D:\a\splat\splat\src\Splat\ServiceLocation\DependencyResolverMixins.cs:line 149
   at Splat.ServiceLocationInitialization.RegisterLogger(IMutableDependencyResolver resolver) in D:\a\splat\splat\src\Splat\ServiceLocation\ServiceLocationInitialization.cs:line 51
   at Splat.ServiceLocationInitialization.InitializeSplat(IMutableDependencyResolver resolver) in D:\a\splat\splat\src\Splat\ServiceLocation\ServiceLocationInitialization.cs:line 27
   at Splat.InternalLocator.<.ctor>b__3_0() in D:\a\splat\splat\src\Splat\ServiceLocation\InternalLocator.cs:line 30
   at Splat.InternalLocator.SetLocator(IDependencyResolver dependencyResolver) in D:\a\splat\splat\src\Splat\ServiceLocation\InternalLocator.cs:line 88
   at Splat.Locator.SetLocator(IDependencyResolver dependencyResolver) in D:\a\splat\splat\src\Splat\ServiceLocation\Locator.cs:line 49
   at Splat.DryIoc.SplatDryIocExtensions.UseDryIocDependencyResolver(IContainer container) in D:\a\splat\splat\src\Splat.DryIoc\SplatDryIocExtensions.cs:line 20
   at Acorisoft.Codaria.SpaModel.RegisterServices(IContainer container) in D:\xxx\Repository\Codaria\src\Acorisoft.xxxaria.UI.ServicePacks\SpaModel.cs:line 67
   at Acorisoft.Codaria.SpaModel..ctor() in D:\xxx\Repository\Codaria\src\Acorisoft.xxxaria.UI.ServicePacks\SpaModel.cs:line 30
   at Acorisoft.Codaria.App..ctor() in Acorisoft.xxxaria.dll:token 0x6000004+0x0
   at Acorisoft.Codaria.App.Main() in Acorisoft.xxxaria.dll:token 0x6000003+0x1

**Comment by glennawatson** [comment]
Using net6 before release is pot luck. Seems to be a breaking change between preview 6 and preview 7.

https://github.com/Azure/Azure-Functions/issues/2015
